PY=python3

sa:
	$(PY) sa.py

sa-tests:
	$(PY) sa_tests.py

tests:
	$(PY) h4_tests.py
	$(PY) h5_tests.py
	$(PY) sa_tests.py

h4:
	$(PY) h4.py

h4-tests:
	$(PY) h4_tests.py

h5:
	$(PY) h5.py

h5-tests:
	$(PY) h5_tests.py


